// Code generated by go-enum
// DO NOT EDIT!

package domain

import (
	"fmt"
)

const (
	// BalanceEventTypeSnapshot is a BalanceEventType of type Snapshot
	BalanceEventTypeSnapshot BalanceEventType = iota
	// BalanceEventTypeUpdate is a BalanceEventType of type Update
	BalanceEventTypeUpdate
)

const _BalanceEventTypeName = "snapshotupdate"

var _BalanceEventTypeMap = map[BalanceEventType]string{
	0: _BalanceEventTypeName[0:8],
	1: _BalanceEventTypeName[8:14],
}

// String implements the Stringer interface.
func (x BalanceEventType) String() string {
	if str, ok := _BalanceEventTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("BalanceEventType(%d)", x)
}

var _BalanceEventTypeValue = map[string]BalanceEventType{
	_BalanceEventTypeName[0:8]:  0,
	_BalanceEventTypeName[8:14]: 1,
}

// ParseBalanceEventType attempts to convert a string to a BalanceEventType
func ParseBalanceEventType(name string) (BalanceEventType, error) {
	if x, ok := _BalanceEventTypeValue[name]; ok {
		return x, nil
	}
	return BalanceEventType(0), fmt.Errorf("%s is not a valid BalanceEventType", name)
}
